### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by mgyatso** [mendix/Atlas-UI-Framework#21]
Hi. Trying to get a head start with the framework before our meeting next week. 

I have downloaded the repository but am wondering if there are some dependencies I need to run Atlas in a browser?

**Comment by Remcovh** [comment]
Hey, 

Well the framework means nothing without the Mendix client. So the best option is to go to https://appstore.home.mendix.com/link/modelers/ download the modeler, create an app, and go to project in the windows file expoler. You will find the css files in the **theme** folder.

**Comment by mgyatso** [comment]
Remco - thank you!
