### ISSUE TITLE
Atlas version number in Mendix

### ISSUE THREAD

**Issue by rickbond79** [mendix/Atlas-UI-Framework#23]
Hi there, are the Atlas version numbers which appear in Mendix under either "Atlas_UI_Framework_Version" or "Atlas_UI_Resources_Version" supposed to match the one on github? If so I think there may be an issue - today I downloaded [Atlas UI 1.2.0 ](https://github.com/mendix/Atlas-UI-Framework/releases/tag/1.2.0) from your github released on Oct 19 but in Mendix it shows as v1.1.0. This is important to me because I'm trying to manage Atlas versioning in multiple Mendix projects using this numbering system as a reference.

![image](https://user-images.githubusercontent.com/2326762/48729279-3d2ab200-ec05-11e8-993e-7e20ae2250b0.png)

**Comment by wesleysieses** [comment]
Both version values are part of the AtlasUI Resources. This means that even if you manually download the AtlasUI Framework and paste it in your theme folder, like you did, it will not change the 'AtlasUI Framework version' value in the modeler. 

The reason v1.1.0 is still displayed as the AtlasUI Framework version, is that there were some delays in updating the AtlasUI Resources in the Mendix starter apps. The new resources will probably be included in the starter apps when there is a new modeler version.

What you can do in the meantime, is download and import the latest AtlasUI Resources from the Mendix app store, which has v1.2.0 of the framework :)

**Comment by rickbond79** [comment]
Hi @wesleysieses thanks for your reply. Makes sense now that you've explained it - cheers!
