### ISSUE TITLE
The browse button for a upload field does nor work after version 1.14

### ISSUE THREAD

**Issue by martijnraats** [mendix/Atlas-UI-Framework#25]

**Comment by wesleysieses** [comment]
Can you be more specific? I guess you are referring to the Atlas Resources v1.1.4.
Which modeler version are you running?
Which widget are you using to upload? 
What do you mean by 'does not work'?
Do you get any error in your mendix/browser console?

**Comment by martijnraats** [comment]
Can you be more specific? I guess you are referring to the Atlas Resources v1.1.4.
Yes

Which modeler version are you running?
7.20.1

Which widget are you using to upload?
FileManager from Mendix (so not a downloaded widget)

What do you mean by 'does not work'?
Clicking on browse does not show the browsefile screen (in chrome).

Do you get any error in your mendix/browser console?
No

**Comment by wesleysieses** [comment]
Thanks for your response. This is not related to the Atlas Framework or Atlas Resources. But I just tested it for you. Everything works as expected. 
Make sure: 
- The filemanager is in a dataview
- The dataview and your filemanager widget is editable
- The entity connected to the dataview has System.FileDocument as Generalization
- The entity is NOT empty, there should be at least 1 object to upload the file to
- The user has the right permissions to access the entity/page and everything related

**Comment by martijnraats** [comment]
The browse button is working fine in Atlas 1.1.4, after upgrading to newer version of Atlas it doesn't work anymore. So it is none of your points, and I do think it is related to Atlas. Since you tested it and cannot reproduce the error I suspect it has something to do with the update process, see also https://forum.mendixcloud.com/link/questions/92007

I replaced my complete theme folder with the master repo if this git, still had the problem.

**Comment by wesleysieses** [comment]
Thanks for the additional information. I was able to successfully reproduce the problem. I released a fix so please update your Atlas Resources through the Mendix App Store. Let me know if that fixes it!

**Comment by martijnraats** [comment]
It works, than you very much!
