### ISSUE TITLE
Need additional classes to use all flex capabilities

### ISSUE THREAD

**Issue by RussellHite** [mendix/Atlas-UI-Framework#33]
I've had several discussion in the recent months with clients and other Mendix developers who are using flex but want more control, but don't want to jump into the SASS.

I've created a gist to extend the _alignment-block.scss partial to include classes for flex-direction, flex-wrap, justify-content, align-items, align-content, and align-self.

https://gist.github.com/RussellHite/5a8cff043e2ebec20415060deb00db8e

**Comment by wesleysieses** [comment]
Nice, flex is definitely the way to go in the future. We are already working hard to implement flex, so this code will help with that. Thanks for sharing!
