### ISSUE TITLE
Issue with display:block; for text alignment classes

### ISSUE THREAD

**Issue by JeroenKesteloo** [mendix/Atlas-UI-Framework#34]
With a new version of the framework the `display: block;` property is set for all text alignment classes that can lead to some weird / unexpected behaviour. It is applied on 3 classes (.text-left, .text-center and .text-right) in the _typography.scss file. It is not possible to undo these display property from the custom.css because display has no "auto" value. 

I would suggest to only apply alignment property to the earlier mentioned classes and create new classes for display proporties if needed.

**Comment by wegiswes** [comment]
Thanks for letting us know. This will be fixed in the next Atlas release.
