### ISSUE TITLE
custom folder does not contain copy of lib

### ISSUE THREAD

**Issue by pimvdnoll** [mendix/Atlas-UI-Framework#4]
The readme stated that there is a copy of the lib folder in the custom folder so you can easily overrule or add custom styling. 

that copy is missing? or should gulp fix this?

**Comment by Remcovh** [comment]
Hi Pim,

Thanks for the heads up! The readme was part of the current framework. Atlas UI Framework is not released yet. We are currently busy finalising the release and will update the readme.

**Comment by Remcovh** [comment]
I totally forgot to answer your question. We decided to keep the custom folder so light as possible. So you only will find there the custom_variable.scss file that contains all variables used by the theme customiser and the custom.scss file that is the starting point for your own customisation. 

The workflow we recommend is to use the lib as an reference and if you want to override styling you create your own file in the custom folder and start coping what you need to override the styling.

I hope this answers your question!

**Comment by pimvdnoll** [comment]
thanks! clear explanation.
